// Demo-data for utvikling uten Supabase

export const demoUser = {
  id: 'demo-user-1',
  email: 'demo@salesfunnel.no',
  first_name: 'Demo',
  last_name: 'Bruker',
  phone: '+47 900 00 000',
}

// Tenant = brukerens egen bedrift (ikke å forveksle med kunde-orgnr)
export const demoTenant = { 
  id: 'demo-tenant-1', 
  name: 'Demo Bedrift AS', 
  created_at: '2024-01-01' 
}

export const demoCustomers = [
  {
    id: 'cust-1',
    tenant_id: 'demo-tenant-1',
    name: 'Nordisk Tech AS',
    org_nr: '912 345 678',
    email: 'kontakt@nordisktech.no',
    phone: '+47 22 33 44 55',
    address: 'Teknologiveien 1',
    postal_code: '0150',
    city: 'OSLO',
    industry: 'Programmeringstjenester',
    employee_count: '25',
    website: 'https://nordisktech.no',
    contact_person: 'Erik Nordmann',
    contact_phone: '+47 900 11 222',
    contact_email: 'erik@nordisktech.no',
    notes: 'Stor interesse for enterprise-løsninger',
    total_sales: 1250000,
    total_profit: 375000,
    margin_percent: 30.0,
    created_at: '2024-03-15',
  },
  {
    id: 'cust-2',
    tenant_id: 'demo-tenant-1',
    name: 'Bergen Handel',
    org_nr: '987 654 321',
    email: 'post@bergenhandel.no',
    phone: '+47 55 66 77 88',
    address: 'Strandgaten 10',
    postal_code: '5013',
    city: 'BERGEN',
    industry: 'Butikkhandel med bredt vareutvalg',
    employee_count: '8',
    website: '',
    notes: 'Oppfølging Q1 2025',
    total_sales: 450000,
    total_profit: 112500,
    margin_percent: 25.0,
    created_at: '2024-04-20',
  },
  {
    id: 'cust-3',
    tenant_id: 'demo-tenant-1',
    name: 'Trondheim Industri AS',
    org_nr: '876 543 210',
    email: 'salg@trd-industri.no',
    phone: '+47 73 88 99 00',
    address: 'Industriveien 50',
    postal_code: '7030',
    city: 'TRONDHEIM',
    industry: 'Produksjon av metallkonstruksjoner',
    employee_count: '45',
    website: 'https://trd-industri.no',
    notes: '',
    total_sales: 2800000,
    total_profit: 560000,
    margin_percent: 20.0,
    created_at: '2024-05-10',
  },
  {
    id: 'cust-4',
    tenant_id: 'demo-tenant-1',
    name: 'Stavanger Consulting',
    org_nr: '765 432 109',
    email: 'hello@stavanger-consulting.no',
    phone: '+47 51 22 33 44',
    address: 'Konsulentgata 5',
    postal_code: '4006',
    city: 'STAVANGER',
    industry: 'Bedriftsrådgivning og annen administrativ rådgivning',
    employee_count: '12',
    website: 'https://stavanger-consulting.no',
    notes: 'Premium-kunde',
    total_sales: 890000,
    total_profit: 356000,
    margin_percent: 40.0,
    created_at: '2024-06-01',
  },
  {
    id: 'cust-5',
    tenant_id: 'demo-tenant-1',
    name: 'Kristiansand Digital',
    org_nr: '654 321 098',
    email: 'info@krs-digital.no',
    phone: '+47 38 11 22 33',
    address: 'Markens gate 20',
    postal_code: '4611',
    city: 'KRISTIANSAND',
    industry: 'Databehandling, datalagring og tilknyttede tjenester',
    employee_count: '5',
    website: '',
    notes: 'Ny lead fra messe',
    total_sales: 0,
    total_profit: 0,
    margin_percent: 0,
    created_at: '2024-07-15',
  },
  {
    id: 'cust-6',
    tenant_id: 'demo-tenant-1',
    name: 'Ole Hansen',
    org_nr: '',
    email: 'ole.hansen@gmail.com',
    phone: '+47 901 23 456',
    address: 'Hjemmeveien 12',
    postal_code: '1234',
    city: 'OSLO',
    industry: '',
    employee_count: '',
    website: '',
    notes: 'Privatkunde - interessert i konsultasjon',
    total_sales: 15000,
    total_profit: 7500,
    margin_percent: 50.0,
    created_at: '2024-08-01',
  },
]

export const demoActivities = [
  // Historiske aktiviteter
  {
    id: 'act-1',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-1',
    user_id: 'demo-user-1',
    type: 'meeting',
    description: 'Første møte - presentasjon av løsning',
    content: 'Gjennomgang av produktdemo. Kunden var interessert i integrasjoner med eksisterende systemer. Avtalt oppfølging om 2 uker.',
    activity_date: '2024-12-20',
    is_scheduled: false,
    is_completed: true,
    customer: { id: 'cust-1', name: 'Nordisk Tech AS' },
  },
  {
    id: 'act-2',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-1',
    user_id: 'demo-user-1',
    type: 'email',
    description: 'Sendt tilbudsdokument',
    content: 'Hei,\n\nVedlagt finner du tilbudet vi diskuterte i møtet.\n\nMvh\nSalgsteamet',
    activity_date: '2024-12-22',
    is_scheduled: false,
    is_completed: true,
    customer: { id: 'cust-1', name: 'Nordisk Tech AS' },
  },
  {
    id: 'act-3',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-2',
    user_id: 'demo-user-1',
    type: 'call',
    description: 'Oppfølgingssamtale',
    content: 'Kunden ønsker demo før nyttår. Booket tid 28. desember.',
    activity_date: '2024-12-18',
    is_scheduled: false,
    is_completed: true,
    customer: { id: 'cust-2', name: 'Bergen Handel' },
  },
  {
    id: 'act-4',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-3',
    user_id: 'demo-user-1',
    type: 'note',
    description: 'Intern notat om kundens behov',
    content: 'Trenger spesialtilpasning for lagerstyring. Snakk med tech-teamet.',
    activity_date: '2024-12-15',
    is_scheduled: false,
    is_completed: true,
    customer: { id: 'cust-3', name: 'Trondheim Industri AS' },
  },
  {
    id: 'act-5',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-4',
    user_id: 'demo-user-1',
    type: 'meeting',
    description: 'Kontraktsforhandling',
    content: 'Enighet om vilkår. Kontrakt signeres i januar.',
    activity_date: '2024-12-28',
    is_scheduled: false,
    is_completed: true,
    customer: { id: 'cust-4', name: 'Stavanger Consulting' },
  },
  // Planlagte aktiviteter (fremtidige)
  {
    id: 'act-6',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-1',
    user_id: 'demo-user-1',
    type: 'meeting',
    description: 'Oppfølgingsmøte etter tilbud',
    content: 'Gå gjennom tilbudet og diskutere eventuelle justeringer.',
    activity_date: '2025-01-02',
    activity_time: '10:00',
    is_scheduled: true,
    is_completed: false,
    customer: { id: 'cust-1', name: 'Nordisk Tech AS' },
  },
  {
    id: 'act-7',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-2',
    user_id: 'demo-user-1',
    type: 'call',
    description: 'Telefonmøte - demo av produkt',
    content: 'Vise frem nye funksjoner i systemet.',
    activity_date: '2024-12-31',
    activity_time: '14:30',
    is_scheduled: true,
    is_completed: false,
    customer: { id: 'cust-2', name: 'Bergen Handel' },
  },
  {
    id: 'act-8',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-3',
    user_id: 'demo-user-1',
    type: 'meeting',
    description: 'Kick-off møte nytt prosjekt',
    content: 'Oppstartsmøte for implementering av ny løsning.',
    activity_date: '2025-01-06',
    activity_time: '09:00',
    is_scheduled: true,
    is_completed: false,
    customer: { id: 'cust-3', name: 'Trondheim Industri AS' },
  },
]

export const demoSales = [
  {
    id: 'sale-1',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-1',
    user_id: 'demo-user-1',
    description: 'Enterprise-lisens årlig',
    amount: 150000,
    sale_date: '2024-10-15',
    notes: 'Inkluderer support',
    customer: { id: 'cust-1', name: 'Nordisk Tech AS' },
  },
  {
    id: 'sale-2',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-2',
    user_id: 'demo-user-1',
    description: 'Standard-pakke',
    amount: 45000,
    sale_date: '2024-11-01',
    notes: '',
    customer: { id: 'cust-2', name: 'Bergen Handel' },
  },
  {
    id: 'sale-3',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-4',
    user_id: 'demo-user-1',
    description: 'Konsulenttime-pakke',
    amount: 85000,
    sale_date: '2024-11-20',
    notes: '10 timer konsulentbistand',
    customer: { id: 'cust-4', name: 'Stavanger Consulting' },
  },
  {
    id: 'sale-4',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-1',
    user_id: 'demo-user-1',
    description: 'Tilleggsmodul - Rapportering',
    amount: 25000,
    sale_date: '2024-12-05',
    notes: '',
    customer: { id: 'cust-1', name: 'Nordisk Tech AS' },
  },
  {
    id: 'sale-5',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-3',
    user_id: 'demo-user-1',
    description: 'Pro-lisens',
    amount: 75000,
    sale_date: '2024-12-10',
    notes: 'Oppgradering fra Basic',
    customer: { id: 'cust-3', name: 'Trondheim Industri AS' },
  },
  {
    id: 'sale-6',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-4',
    user_id: 'demo-user-1',
    description: 'Årlig vedlikehold',
    amount: 35000,
    sale_date: '2024-09-01',
    notes: '',
    customer: { id: 'cust-4', name: 'Stavanger Consulting' },
  },
  // Nye salg for desember 2025 (for å vise i statistikk)
  {
    id: 'sale-7',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-1',
    user_id: 'demo-user-1',
    description: 'Konsulentbistand des',
    amount: 45000,
    sale_date: '2025-12-15',
    notes: '',
    customer: { id: 'cust-1', name: 'Nordisk Tech AS' },
  },
  {
    id: 'sale-8',
    tenant_id: 'demo-tenant-1',
    customer_id: 'cust-3',
    user_id: 'demo-user-1',
    description: 'Serviceavtale',
    amount: 12500,
    sale_date: '2025-12-20',
    notes: '',
    customer: { id: 'cust-3', name: 'Trondheim Industri AS' },
  },
]

export const demoMembers = [
  {
    id: 'member-1',
    tenant_id: 'demo-tenant-1',
    user_id: 'demo-user-1',
    role: 'owner',
    user: { id: 'demo-user-1', email: 'demo@salesfunnel.no' },
  },
]

// Helper for å generere unike IDer
export const generateId = () => `demo-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`
